services:
  - type: web
    name: mern-backend
    env: node
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://ahmed14massoud2021:SpIQShTSjBGHh8Wy@cluster0.mcgxpjj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      - key: PORT
        value: "10000"
      - key: JWT_SECRET
        value: "abac12afsdkjladf"

