services:
  - type: web
    name: mern-backend
    env: node
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://username:password@cluster.mongodb.net/dbname"
      - key: PORT
        value: "10000"
